#!/usr/bin/env bash
# Usage: test-ln [--noop]
# Only @nobe4 can run this.

set -e

NOOP='false'
if [[ "$1" == "--noop" ]]; then
	NOOP='true'
fi

go run cmd/gh-ln/main.go \
	-token "$(gh auth token)" \
	-repo "frozen-fishsticks/action-ln-test-0" \
	-config "ln-config.yaml" \
	-noop "${NOOP}" \
	-debug
