#!/usr/bin/env bash
# Usage: test-ln [--noop]
# Only @nobe4 can run this.

set -e

NOOP='false'
if [[ "$1" == "--noop" ]]; then
	NOOP='true'
fi

GITHUB_TOKEN=$(gh auth token) \
	INPUT_CONFIG=ln-config.yaml \
	GITHUB_REPOSITORY=frozen-fishsticks/action-ln-test-0 \
	RUNNER_DEBUG=1 \
	INPUT_NOOP="${NOOP}" \
	go run cmd/gh-ln/main.go
