#!/usr/bin/env bash
# Only @nobe4 can run this.

set -e

GITHUB_TOKEN=$(gh auth token) \
	GITHUB_REPOSITORY=nobe4/gh-ln \
	RUNNER_DEBUG=1 \
	INPUT_NOOP=1 \
	INPUT_LOCAL_CONFIG=".ln-config.yaml" \
	go run cmd/gh-ln/main.go
